---  
- hosts: webservers  
  tasks:
  - name: debconf phpmyadmin'i jaoks
    debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

  - name: debconf phpmyadmin'i jaoks
    debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{mysql_root_pass}}' vtype='password'

  - name: debconf phpmyadmin'i jaoks
    debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{mysql_root_pass}}' vtype='password'

  - name: debconf phpmyadmin'i jaoks
    debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{mysql_root_pass}}' vtype='password'

  - name: debconf phpmyadmin'i jaoks
    debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

  - name: installime phpmyadmin
    apt: pkg=phpmyadmin state=present

  - name: konfigureerimis sait
    file: path=/var/www/phpmyadmin src=/usr/share/phpmyadmin state=link
