---
- hosts: webservers
  tasks:
  - name: Loome mysql andmebaasi wordpressi jaoks
    mysql_db:
      name: wpdatabase
      state: present

  - name: Loome mysql kasutaja wpuser
    mysql_user:
      name: wpuser
      password: qwerty
      priv: 'wpdatabase.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes
  - name: alglaadimine mysql
    service: name=mysql state=restarted

  - name: Wordpressi installimine ning lahti pakkimine
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Vahetame wordpress kausta omanikuks www-data
    file:
      path: /var/www/html/wordpress/
      state: directory
      recurse: yes
      owner: www-data

  - name: Kopeerime config fail
    command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

  - name: Vahetame iDB_PASSWORD wordpressi config failis
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="password_here'" line="define( 'DB_PASSWORD', 'qwerty' );"

  - name: Vahetame DB_USER wordpressi config failis
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="username_here" line="define( 'DB_USER', 'wpuser' );"

  - name: Vahetame DB_NAME wordpressi config failis
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="database_name_here" line="define( 'DB_NAME', 'wpdatabase' );"
